// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	model "weatherService/pkg/model"

	mock "github.com/stretchr/testify/mock"
)

// FavouriteRepository is an autogenerated mock type for the FavouriteRepository type
type FavouriteRepository struct {
	mock.Mock
}

// AddCityToFavourite provides a mock function with given fields: personId, cityId
func (_m *FavouriteRepository) AddCityToFavourite(personId int, cityId int) error {
	ret := _m.Called(personId, cityId)

	if len(ret) == 0 {
		panic("no return value specified for AddCityToFavourite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(personId, cityId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllFavouriteCity provides a mock function with given fields: personId
func (_m *FavouriteRepository) GetAllFavouriteCity(personId int) ([]model.City, error) {
	ret := _m.Called(personId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllFavouriteCity")
	}

	var r0 []model.City
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]model.City, error)); ok {
		return rf(personId)
	}
	if rf, ok := ret.Get(0).(func(int) []model.City); ok {
		r0 = rf(personId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.City)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(personId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFavouriteRepository creates a new instance of FavouriteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFavouriteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FavouriteRepository {
	mock := &FavouriteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
