CREATE TABLE city
(
    id      int generated by default as identity primary key,
    name    varchar(100) not null unique,
    country varchar(100) not null,
    lat     real         not null,
    lon     real         not null
);

create table weather_forecast
(
    id      int generated by default as identity primary key,
    date    date not null,
    temp    real not null,
    data    varchar,
    city_id int references city (id) on delete cascade,
    unique (city_id, date)
);