create table city
(
    id      int generated by default as identity primary key,
    name    varchar(100) not null unique,
    country varchar(100) not null,
    lat     real         not null,
    lon     real         not null
);

create table weather_forecast
(
    id      int generated by default as identity primary key,
    date    timestamp not null,
    temp    real      not null,
    data    json,
    city_id int references city (id) on delete cascade,
    unique (city_id, date)
);

create index idx_weather_forecast_city_id on weather_forecast (city_id);

create table person
(
    id       int generated by default as identity primary key,
    username varchar(100) unique not null,
    password varchar(100)        not null
);

create table favourite
(
    person_id int references person (id) on delete cascade,
    city_id   int references city (id) on delete cascade,
    primary key (person_id, city_id)
);